<?php

namespace AppBundle\Repository;

/**
 * StadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumRepository extends \Doctrine\ORM\EntityRepository
{
}
